version: "3"
services:
  server:
    build:
      context: ./server/
    depends_on:
      - postgres
    command: /usr/app/node_modules/.bin/nodemon src/index.js
    volumes:
      - ./server/:/usr/app
      - /usr/app/node_modules
    ports:
      - "5001:5000"
    # env_file: ./server/.env
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:pass@postgres:5432/test_db
  client:
    build:
      context: ./client/
    command: npm start
    volumes:
      - ./client/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - server
    ports:
      - "3001:3000"
  postgres:
    image: postgres:11
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: test_db
    container_name: postgres
volumes:
  db-data: